### ISSUE TITLE
FetchBalance

### ISSUE THREAD

**Issue by R3T1K0** [CDTtrix/Discordenvo#3]
Hi! I downloaded this package and i added my fetchBalance script but it does not fetch... Well: It gets it but like this...
![Screenshot_192](https://user-images.githubusercontent.com/49074962/71470345-21acb600-27cc-11ea-8397-922240f9b0ff.png)
`    if (command === "bal" || command === "balance") {
        const tempBal = await eco.FetchBalance(message.author.id)
        const embed = new Discord.RichEmbed()
        .setTitle(message.author.tag)
        .setThumbnail(message.author.avatarURL)
        .setColor("#1e90ff")
        .addField("Balance", tempBal)
        message.channel.send(embed)
    }`

**Comment by CDTtrix** [comment]
the fetchBalance function has properties like when you say tempbal its a promise
but when you say tempbal.balance it returns the balance of the user i advise you to look through the example bot you should join https://discord.gg/Ym5BnJU for more help
